# Generated by Django 3.2.4 on 2021-06-27 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='member_profiles'),
        ),
        migrations.AddField(
            model_name='memberserver',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='server_profiles'),
        ),
        migrations.AlterField(
            model_name='member',
            name='discord_username',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
