# Generated by Django 3.2.4 on 2021-06-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersites', '0002_auto_20210627_2035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='member_profiles'),
        ),
        migrations.AlterField(
            model_name='memberserver',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='server_profiles'),
        ),
    ]
